name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "src/app"  # Change this to the path of your built Flask app
        target: "/home/ec2-user/orm"
        
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 43.207.165.181 >> ~/.ssh/known_hosts

    - name: Install deps and Start Gunicorn Server
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} 'kill -9 $(lsof -t -i:5000) && source /home/ec2-user/venv/bin/activate && source ~/.bashrc && pip install -r /home/ec2-user/orm/src/app/requirements.txt && cd /home/ec2-user/orm/ && nohup gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 2 --timeout 0 src.app.app:app > gunicorn.log 2>&1 &'
