name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Install dependencies and build
#      run: |
#        source venv/bin/activate
#        cd src/app
#        pip install -r requirements.txt
#        # Add any additional build steps here

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "src/app"  # Change this to the path of your built Flask app
        target: "/home/ec2-user/orm"

    - name: Print current working directory
      run: |
        pwd
        ls

    - name: Start Gunicorn Server
      run: |
        nohup exec gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 2 --timeout 0 src.app.app:app > gunicorn.log 2>&1 &
