name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        cd src/app/
        pip install -r requirements.txt
        # Add any additional build steps here

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "src/app"  # Change this to the path of your built Flask app
        target: "/home/ec2-user/orm"

    - name: Start Gunicorn Server
      run: |
        cd /home/ec2-user/orm
        nohup exec gunicorn --bind :$PORT --workers 1 --threads 2 --timeout 0 src.app.app:app > gunicorn.log 2>&1 &